apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: auth-mysql-depl
spec:
  selector:
    matchLabels:
      app: auth-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-mysql
    spec:
      containers:
        - image: mysql:5.7
          name: auth-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mysql-srv
spec:
  selector:
    app: auth-mysql
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
