apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-mysql-depl
spec:
  selector:
    matchLabels:
      app: profile-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: profile-mysql
    spec:
      containers:
        - image: mysql:5.7
          name: profile-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: profile-mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: profile-mysql-srv
spec:
  selector:
    app: profile-mysql
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
